name: Deploy to AWS (Prod)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install Serverless
        run: npm install -g serverless

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Serverless
        run: serverless deploy
        env:
          ENV: prod